---@meta _

---@class Action
---@field ActionType string
---@field CastTime? number
---@field Element? string
---@field Id number
---@field MpCost? number
---@field MpAftercast? number
---@field MppAftercast? number
---@field Name string
---@field Recast? string
---@field Resend boolean
---@field Resource? userdata
---@field Skill? string
---@field Type string