---@meta _

---@class PetAction
---@field ActionType string
---@field CastTime? number
---@field Element? string
---@field Id number
---@field MpCost? number
---@field Name string
---@field Recast? string
---@field Resend boolean
---@field Resource? table
---@field Skill? string
---@field Type string